[package]
name = "intercode_warp_core"
version = "0.1.0"
edition = "2021"
authors = ["Nat Budin <nbudin@actbluetech.com>"]
license = "MIT"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = { version = "0.4" }
